server:
  port: 7000
spring:
  application:
    name: servidor-gateway
  cloud:
    gateway:
      routes:
        - id: servicio-vuelos
          uri: lb://servicio-vuelos/
          predicates:
            - Path=/svuelos/**
          filters:
            - RewritePath=/svuelos/*, /
        - id: servicio-reservas
          uri: lb://servicio-reservas/
          predicates:
            - Path=/sreservas/**
          filters:
            - RewritePath=/sreservas/*, /
        - id: servicio-hotel
          uri: lb://servicio-hoteles/
          predicates:
            - Path=/shoteles/**
          filters:
            - RewritePath=/shoteles/*, /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
