server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/viajes?serverTimezone=Europe/Madrid&useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

